services:

  #Imagen del pgadmin
  postgres:
    image: postgres:16
    container_name: postgres-db

    environment:
      POSTGRES_DB: marketplace
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

      #Imagen del pgadmin
  pgadmin:
    image: dpage/pgadmin4

    container_name: pgadmin

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@test.com
      PGADMIN_DEFAULT_PASSWORD: 123456

    ports:
      - "5050:80"

    depends_on:
      - postgres


      #Microservicio Usuarios
  usuarios:
    build:
      context: ./Usuarios

    container_name: usuarios-service

    ports:
      - "8081:8081"

    depends_on:
      - postgres

    environment:

      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: marketplace
      DB_USER: admin
      DB_PASSWORD: 123456


      #Microservicio Articulos
  articulos:
    build:
      context: ./Articulos

    container_name: articulos-service

    ports:
      - "8082:8082"

    depends_on:
      - postgres

    environment:

      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: marketplace
      DB_USER: admin
      DB_PASSWORD: 123456


      #Microservicio: Ventas
  ventas:
    build:
      context: ./Ventas

    container_name: ventas-service

    ports:
      - "8083:8083"

    depends_on:
      - postgres

    environment:

      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: marketplace
      DB_USER: admin
      DB_PASSWORD: 123456


      #Aplicación: Angular
  angular:
    build:
      context: ./marketplace

    container_name: marketplace

    ports:
      - "4200:4200"

    depends_on:
      - usuarios
      - articulos
      - ventas



volumes:

  postgres-data: