services:
  #Imagen para la base de datos postgresql
  postgres_db:
    image: postgres:17-alpine
    container_name: postgres-db-m
    environment:
      POSTGRES_DB: Marketplace
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
    ports:
      - "5432:5432"
    volumes:
      - ./dbfiles:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    networks:
      - senen-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d Marketplace" ]
      interval: 10s
      timeout: 5s
      retries: 5
  #Administrador pgadmin para ver la base posgtresql
  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: senen@email.com
      PGADMIN_DEFAULT_PASSWORD: Mudkip
    ports:
      - "80:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres_db:
        condition: service_healthy
    networks:
      - senen-network

  #Imagen para Articulos
  articulos:
    build:
      context: ./Backend/Articulos
      dockerfile: Dockerfile
    image: marketplace/articulo-service:1.0-SNAPSHOT
    container_name: articulos-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/Marketplace
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: qwerty
    ports:
      - "8000:8001"
    depends_on:
      postgres_db:
        condition: service_healthy
    restart: on-failure
    networks:
      - senen-network

  #Imagen para Ventas
  ventas:
    build:
      context: ./Backend/Ventas
      dockerfile: Dockerfile
    image: marketplace/ventas-service:1.0-SNAPSHOT
    container_name: ventas-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/Marketplace
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: qwerty
    ports:
      - "8001:8002"
    depends_on:
      postgres_db:
        condition: service_healthy
    restart: on-failure
    networks:
      - senen-network

  #Imagen para Usuarios
  usuarios:
    build:
      context: ./Backend/Usuarios
      dockerfile: Dockerfile
    image: marketplace/usuarios-service:1.0-SNAPSHOT
    container_name: usuarios-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/Marketplace
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: qwerty
    ports:
      - "8002:8003"
    depends_on:
      postgres_db:
        condition: service_healthy
    restart: on-failure
    networks:
      - senen-network
#Nota: volumes y network, van fuera de services.
volumes:
  postgres_data:
  pgadmin_data:

networks:
  senen-network:
