spring.application.name=Ventas
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#Credenciales para base de datos local
spring.datasource.url=jdbc:postgresql://localhost:5432/Marketplace
spring.datasource.username=postgres
spring.datasource.password=Mudkip
server.port=8002