spring.application.name=Articulos
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#Credenciales para base de datos local
#spring.datasource.url=jdbc:postgresql://localhost:5432/Marketplace
#spring.datasource.username=postgres
#spring.datasource.password=Mudkip
#Credenciales para base de datos en docker
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/Marketplace}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:qwerty}
server.port=8001
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB